'use strict';

// Vertical content library. All copy reads as real and brand-plausible.
// The {b} token is interpolated with the brand name at generate time.
// Prices are stored as plain integers; the currency symbol is applied (and
// entity-encoded) by generate.js so the same content works for any currency.

const VERTICALS = ['Fashion', 'Food', 'Finance', 'Beauty', 'Electronics', 'Travel', 'Generic'];

// Tone-driven headline templates. {b} = brand.
const TONES = {
  Playful: {
    reveal: 'Psst {b} has a little something for you',
    quiz: 'Which {b} pick is your vibe?',
    poll: 'Settle it for us, {b} fan',
    rate: 'How did we do? Be honest!',
    spin: 'Feeling lucky? Give it a whirl',
    search: 'Hunt down your next {b} favourite',
    calc: 'Tap tap watch your {b} numbers move',
    report: 'Your {b} report card just landed',
  },
  Premium: {
    reveal: 'An exclusive {b} offer, curated for you',
    quiz: 'Discover the {b} edit made for you',
    poll: 'Help shape the next {b} collection',
    rate: 'Your impression of {b} matters',
    spin: 'Unlock a members-only {b} reward',
    search: 'Explore the {b} collection',
    calc: 'Model your {b} plan, precisely',
    report: 'Your private {b} statement, prepared at open',
  },
  Urgent: {
    reveal: 'Your {b} offer expires tonight open now',
    quiz: 'Find your match before the sale ends',
    poll: 'Last chance to vote {b} drops soon',
    rate: 'Quick rate your last {b} order',
    spin: 'One spin left claim your {b} deal now',
    search: 'Selling fast find yours before it goes',
    calc: 'Run the numbers before the window closes',
    report: 'Your {b} results need a look today',
  },
  Informative: {
    reveal: 'A new offer is available on your {b} account',
    quiz: 'Answer one question for a tailored {b} pick',
    poll: 'Share your preference with the {b} team',
    rate: 'Rate your recent experience with {b}',
    spin: 'Spin to see your available {b} reward',
    search: 'Search the full {b} catalogue',
    calc: 'Estimate it yourself, right in this email',
    report: 'Your {b} summary is ready to review',
  },
};

const CONTENT = {
  Fashion: {
    items: [
      { name: 'Linen Resort Shirt', price: 2499 },
      { name: 'High-Rise Tailored Trousers', price: 3299 },
      { name: 'Suede Chelsea Boots', price: 4799 },
      { name: 'Oversized Knit Sweater', price: 2899 },
      { name: 'Pleated Midi Skirt', price: 1999 },
      { name: 'Cropped Denim Jacket', price: 3599 },
    ],
    categories: ['Apparel', 'Footwear', 'Accessories'],
    catKeys: ['apparel', 'footwear', 'accessories'],
    itemCats: ['apparel', 'apparel', 'footwear', 'apparel', 'apparel', 'apparel'],
    quiz: {
      q: 'What is your go-to weekend look?',
      options: [
        { label: 'Effortless & casual', result: 'You will love the {b} relaxed linen edit comfort first, always.' },
        { label: 'Sharp & tailored', result: 'The {b} tailoring line is calling clean lines, smart fits.' },
        { label: 'Bold statement', result: 'Go big with the {b} statement collection colour and texture that turn heads.' },
      ],
    },
    poll: { q: 'Which drop should {b} restock first?', a: 'Suede boots', b: 'Knit sweaters' },
    rate: 'How would you rate your latest {b} order?',
    calc: {
      calcType: 'plan',
      promptText: 'Express delivery and free returns on every order, or one flat pass — tap your usage and watch the maths.',
      aLabel: 'Orders a month', bLabel: 'People on the pass',
      aOptions: [1, 2, 3, 4, 6], bOptions: [1, 2, 3, 4],
      perUseFee: 199, planPrice: 299,
      resultLabel: 'You would save every month',
      ctaLabel: 'Try the {b} pass',
      doneLabel: 'Request sent — finish in the {b} app',
      dividerLabel: 'Living layer · composed at open',
      receiptTag: 'Untouched · your account',
      receiptRows: [
        { k: 'Member', v: 'Ananya S.' },
        { k: 'Orders this season', v: '7 delivered · 1 returned' },
        { k: 'Saved fit', v: 'M · UK 5' },
      ],
      footerText: 'Estimates use your last 90 days of orders. Nothing is ever charged inside this email.',
    },
    report: {
      reportNoun: 'order update', itemNoun: 'items',
      receiptTag: 'Untouched · transactional',
      metaRows: [
        { k: 'Order', v: 'ORD-2026-48261' },
        { k: 'Placed', v: 'Sun 6 Jul, 11:42 am' },
        { k: 'Deliver to', v: 'Home · 560034' },
      ],
      attachmentName: 'Tax-Invoice-ORD48261.pdf',
      attachmentMeta: '1 page · secure download',
      dividerLabel: 'Live status · composed at open',
      statusLabels: { normal: 'On schedule', attention: 'Delayed' },
      rows: [
        { name: 'Linen Resort Shirt', sub: 'Sand · size M', value: 'Out for delivery', status: 'normal', detail: 'Left the hub at 8:10 am with your usual courier. Expected before 6 pm today — no signature needed.' },
        { name: 'High-Rise Tailored Trousers', sub: 'Charcoal · size 28', value: 'Shipped', status: 'normal', detail: 'In transit from the Bengaluru warehouse. On track for Thursday.' },
        { name: 'Suede Chelsea Boots', sub: 'Tan · UK 5', value: 'Delayed +2 days', status: 'attention', detail: 'Weather held up the line-haul. New window: Sat–Sun. A delivery-fee refund has already been applied — nothing to claim.' },
        { name: 'Pleated Midi Skirt', sub: 'Ivory · size S', value: 'Packed', status: 'normal', detail: 'Sealed and labelled, waiting for the next pickup slot at the warehouse.' },
        { name: 'Cropped Denim Jacket', sub: 'Mid-wash · size M', value: 'Quality check', status: 'normal', detail: 'Every {b} denim piece gets a stitch-and-wash check before it ships. Usually clears within a day.' },
      ],
      verdictAction: 'one parcel is running late, and the delivery fee has already been refunded.',
      verdictCta: 'What does this mean?',
      nextPrompt: 'Where should the delayed parcel go?',
      slotLabels: ['Leave at door', 'Pickup point', 'With the neighbour'],
      pickPrompt: 'Pick a drop-off first',
      ctaLabel: 'Save preference',
      doneLabel: '✓ Saved — the courier has been told',
      footerText: 'Order status is fetched live at the moment you open this email.',
    },
  },
  Food: {
    items: [
      { name: 'Wood-Fired Margherita', price: 399 },
      { name: 'Truffle Mushroom Risotto', price: 549 },
      { name: 'Korean Fried Chicken Bucket', price: 649 },
      { name: 'Smash Burger Combo', price: 449 },
      { name: 'Mango Sticky Rice', price: 249 },
      { name: 'Cold Brew Flask', price: 299 },
    ],
    categories: ['Mains', 'Sides', 'Desserts'],
    catKeys: ['mains', 'sides', 'desserts'],
    itemCats: ['mains', 'mains', 'mains', 'mains', 'desserts', 'sides'],
    quiz: {
      q: 'How hungry are we tonight?',
      options: [
        { label: 'Light & fresh', result: 'The {b} fresh bowls menu is perfect light, fast, and full of flavour.' },
        { label: 'Comfort cravings', result: 'Time for {b} comfort classics melty, crispy, exactly what you need.' },
        { label: 'Feed the squad', result: 'Order the {b} sharing platters built to feed the whole table.' },
      ],
    },
    poll: { q: 'What should {b} add to the menu next?', a: 'Spicy ramen', b: 'Loaded fries' },
    rate: 'How was your last meal from {b}?',
    calc: {
      calcType: 'plan',
      promptText: 'Delivery and packing fees on every order, or the household pass — tap your month and see the difference.',
      aLabel: 'Orders a month', bLabel: 'People ordering',
      aOptions: [2, 4, 8, 12, 16], bOptions: [1, 2, 3, 4],
      perUseFee: 49, planPrice: 149,
      resultLabel: 'You would save every month',
      ctaLabel: 'Start the {b} pass',
      doneLabel: 'Request sent — confirm in the {b} app',
      dividerLabel: 'Living layer · composed at open',
      receiptTag: 'Untouched · your account',
      receiptRows: [
        { k: 'Account', v: 'Ananya S.' },
        { k: 'Last order', v: 'Tue · delivered in 31 min' },
        { k: 'Usual spot', v: 'Home · 560034' },
      ],
      footerText: 'Fees estimated from your last 10 orders. Nothing is ever charged inside this email.',
    },
    report: {
      reportNoun: 'monthly summary', itemNoun: 'habits',
      receiptTag: 'Untouched · your account',
      metaRows: [
        { k: 'Summary', v: 'JUN-2026 · NMD9261837' },
        { k: 'Orders covered', v: '9 orders · 5 places' },
      ],
      dividerLabel: 'Personalised for you · composed at open',
      statusLabels: { normal: 'On track', attention: 'Worth a look' },
      rows: [
        { name: 'Orders in June', sub: 'Across 5 restaurants', value: '9', status: 'normal', detail: 'Right around your six-month average. Your most-ordered: Wood-Fired Margherita, three times.' },
        { name: 'Average delivery time', sub: 'Door to door', value: '29 min', status: 'normal', detail: '4 minutes faster than May — two of your favourites moved to a nearer kitchen.' },
        { name: 'Late-night orders', sub: 'After 11 pm', value: '5 of 9', status: 'attention', detail: 'More than half your orders land late — night kitchens near you now run till 2 am, and lighter menus are one tap away.' },
        { name: 'Spend vs May', sub: 'Food + fees', value: '+₹1,240', status: 'attention', detail: 'Most of the jump is delivery fees on small late-night orders. The pass would have absorbed ₹294 of it.' },
        { name: 'Free deliveries used', sub: 'Pass benefits', value: '6 of 9', status: 'normal', detail: 'Three orders fell outside pass hours. Kitchens on the pass now cover 92% of your area.' },
      ],
      verdictAction: 'late-night fees are quietly adding up — the pass would have covered them.',
      verdictCta: 'See what it means',
      nextPrompt: 'Make July cheaper?',
      slotLabels: ['Order my usual', 'Show lighter picks', 'Set a monthly cap'],
      pickPrompt: 'Pick an option first',
      ctaLabel: 'Done',
      doneLabel: '✓ Set — visible in your {b} app',
      footerText: 'A summary of your own orders, composed when you opened this email.',
    },
  },
  Finance: {
    items: [
      { name: 'Index Fund Starter Plan', price: 500 },
      { name: 'Digital Gold (per gram)', price: 7200 },
      { name: 'Tax-Saver ELSS Bundle', price: 5000 },
      { name: 'Fixed Deposit Booster', price: 10000 },
      { name: 'Micro-SIP Auto Invest', price: 100 },
      { name: 'Liquid Fund Wallet', price: 1000 },
    ],
    categories: ['Invest', 'Save', 'Insure'],
    catKeys: ['invest', 'save', 'insure'],
    itemCats: ['invest', 'invest', 'invest', 'save', 'invest', 'save'],
    quiz: {
      q: 'What is your money goal this year?',
      options: [
        { label: 'Grow wealth', result: 'Explore the {b} equity baskets built for long-term growth.' },
        { label: 'Save steadily', result: 'Set up a {b} auto-SIP small, consistent, powerful.' },
        { label: 'Stay protected', result: 'The {b} protection plans keep your goals safe whatever comes.' },
      ],
    },
    poll: { q: 'What matters most in a {b} app?', a: 'Lower fees', b: 'Better insights' },
    rate: 'How likely are you to recommend {b}?',
    calc: {
      calcType: 'sip',
      promptText: 'Tap a monthly amount and a horizon — the corpus updates instantly, working shown.',
      aLabel: 'Monthly SIP', bLabel: 'Invested for',
      aOptions: [1000, 2500, 5000, 10000, 25000], bOptions: [1, 3, 5, 10, 15, 20, 25],
      ratePct: 12,
      resultLabel: 'Estimated corpus',
      ctaLabel: 'Set up this SIP',
      doneLabel: 'Request sent — approve in your {b} app',
      dividerLabel: 'Living layer · composed at open',
      receiptTag: 'Untouched · your folio',
      receiptRows: [
        { k: 'Folio', v: 'FOL-88412031' },
        { k: 'Last SIP debit', v: '3 Jul · on time' },
        { k: 'KYC', v: 'Verified' },
      ],
      footerText: 'Illustration at an assumed rate, not a promise of returns. Mutual fund investments are subject to market risks.',
    },
    report: {
      reportNoun: 'statement', itemNoun: 'holdings',
      receiptTag: 'Untouched · transactional',
      metaRows: [
        { k: 'Statement', v: 'STMT-2026-77120' },
        { k: 'Period', v: '1–30 Jun 2026' },
        { k: 'Linked bank', v: 'HDFC ····4021' },
      ],
      attachmentName: 'Portfolio-Statement-Jun-2026.pdf',
      attachmentMeta: '2 pages · secure download',
      dividerLabel: 'Personalised for you · composed at open',
      statusLabels: { normal: 'On track', attention: 'Worth a look' },
      rows: [
        { name: 'Nifty 50 Index Fund', sub: 'SIP · ₹5,000/mo', value: '+11.8%', unit: 'XIRR', status: 'normal', detail: 'Your longest-running SIP, 26 instalments in. Staying invested through the March dip is what earned this number.' },
        { name: 'HDFC Bank', sub: '12 shares · avg ₹1,522', value: '₹1,684.20', status: 'normal', detail: 'Up 10.7% on your average buy price. A movie, not a snapshot — day moves matter less than your holding period.' },
        { name: 'TCS', sub: '4 shares · avg ₹3,940', value: '₹3,812.10', status: 'attention', detail: 'Down 3.2% on your average buy — IT has lagged the index this quarter. General information, not personal advice.' },
        { name: 'Smallcap Momentum Fund', sub: 'Lump sum · Mar 2026', value: '-6.4%', status: 'attention', detail: 'Smallcaps swing hardest both ways. This is 4% of your portfolio, so the drawdown costs you less than it looks.' },
        { name: 'Digital Gold', sub: '2.4 g accumulated', value: '+4.1%', status: 'normal', detail: 'Doing its job as ballast — it moved opposite your equity twice this quarter.' },
        { name: 'Liquid Fund', sub: 'Emergency buffer', value: '+1.7%', status: 'normal', detail: 'Covers about 3.2 months of your average spending. Six is the usual target.' },
      ],
      verdictAction: 'a 10-minute rebalance brings you back to plan.',
      verdictCta: 'See what it means',
      nextPrompt: 'Talk it through',
      slotLabels: ['Call from an advisor', 'Email the breakdown', 'Rebalance in the app'],
      pickPrompt: 'Pick an option first',
      ctaLabel: 'Confirm',
      doneLabel: '✓ Done — details on the way',
      footerText: 'This summary is informational, not investment advice.',
    },
  },
  Beauty: {
    items: [
      { name: 'Vitamin C Glow Serum', price: 899 },
      { name: 'Hydra-Plump Moisturiser', price: 1199 },
      { name: 'Matte Liquid Lipstick', price: 599 },
      { name: 'Satin Foundation Stick', price: 1399 },
      { name: 'Rosewater Setting Mist', price: 749 },
      { name: 'Overnight Repair Mask', price: 999 },
    ],
    categories: ['Skincare', 'Makeup', 'Tools'],
    catKeys: ['skincare', 'makeup', 'tools'],
    itemCats: ['skincare', 'skincare', 'makeup', 'makeup', 'skincare', 'skincare'],
    quiz: {
      q: 'What does your skin want today?',
      options: [
        { label: 'A radiant glow', result: 'The {b} brightening range is your match hello, glow.' },
        { label: 'Deep hydration', result: 'Reach for the {b} hydration heroes thirsty skin, sorted.' },
        { label: 'A bold lip', result: 'The {b} colour studio has the shade long-wear, full pigment.' },
      ],
    },
    poll: { q: 'Which {b} shade range needs more love?', a: 'Warm tones', b: 'Cool tones' },
    rate: 'How happy are you with your {b} haul?',
    calc: {
      calcType: 'plan',
      promptText: 'Salon-at-home sessions one at a time, or the membership — tap how often you book and see what stays in your pocket.',
      aLabel: 'Sessions a month', bLabel: 'People sharing it',
      aOptions: [1, 2, 3, 4], bOptions: [1, 2, 3],
      perUseFee: 799, planPrice: 999,
      resultLabel: 'You would save every month',
      ctaLabel: 'Hold my membership',
      doneLabel: 'Held — pay in the {b} app, never in email',
      dividerLabel: 'Living layer · composed at open',
      receiptTag: 'Untouched · your account',
      receiptRows: [
        { k: 'Member', v: 'Ananya S.' },
        { k: 'Last session', v: 'Facial · 28 Jun' },
        { k: 'Preferred stylist', v: 'Meera · 4.9★' },
      ],
      footerText: 'Session price is your city average. Nothing is ever charged inside this email.',
    },
    report: {
      reportNoun: 'routine check-in', itemNoun: 'products',
      receiptTag: 'Untouched · your shelf',
      metaRows: [
        { k: 'Routine', v: '5 products · AM + PM' },
        { k: 'Tracked since', v: 'March 2026' },
      ],
      dividerLabel: 'Personalised for you · composed at open',
      statusLabels: { normal: 'Stocked', attention: 'Running low' },
      rows: [
        { name: 'Vitamin C Glow Serum', sub: 'Opened 12 May', value: '~11 days left', status: 'attention', detail: 'At your logged pace (5 drops, most mornings) this runs out around the 22nd. A refill ships in 2 days.' },
        { name: 'Hydra-Plump Moisturiser', sub: 'Opened 3 Jun', value: '~26 days left', status: 'normal', detail: 'Comfortably stocked. Humid-season tip: a pea-size amount is enough, so it may stretch further.' },
        { name: 'SPF 50 Sunscreen', sub: 'Daily use', value: '~6 days left', status: 'attention', detail: 'Daily-wear SPF always empties first — it is the one product worth never running out of.' },
        { name: 'Overnight Repair Mask', sub: 'Opened 2 Jul', value: 'Fresh', status: 'normal', detail: 'Barely used. Twice a week is the sweet spot — more will not speed it up.' },
        { name: 'Rosewater Setting Mist', sub: 'Opened 20 May', value: '~30 days left', status: 'normal', detail: 'On pace with your routine. No action needed.' },
      ],
      verdictAction: 'two dailies are about to run out — a refill now beats a gap week.',
      verdictCta: 'See what it means',
      nextPrompt: 'Sort the refills',
      slotLabels: ['Refill the low ones', 'Refill full routine', 'Remind me next week'],
      pickPrompt: 'Pick an option first',
      ctaLabel: 'Queue it',
      doneLabel: '✓ Queued — approve payment in the app',
      footerText: 'Levels estimated from your routine log. Informational, not dermatological advice.',
    },
  },
  Electronics: {
    items: [
      { name: 'Noise-Cancelling Earbuds', price: 4999 },
      { name: 'Smartwatch Series X', price: 8999 },
      { name: 'Mechanical Keyboard', price: 5499 },
      { name: '4K Action Camera', price: 12999 },
      { name: 'Fast-Charge Power Bank', price: 1799 },
      { name: 'Portable SSD 1TB', price: 6499 },
    ],
    categories: ['Audio', 'Wearables', 'Accessories'],
    catKeys: ['audio', 'wearables', 'accessories'],
    itemCats: ['audio', 'wearables', 'accessories', 'accessories', 'accessories', 'accessories'],
    quiz: {
      q: 'What upgrade are you after?',
      options: [
        { label: 'Better sound', result: 'The {b} audio line is calling immersive, crisp, wireless.' },
        { label: 'Smarter tracking', result: 'Level up with {b} wearables your day, quantified.' },
        { label: 'Faster workflow', result: 'The {b} pro accessories shave seconds off every task.' },
      ],
    },
    poll: { q: 'What should {b} launch next?', a: 'Foldable phone', b: 'AR glasses' },
    rate: 'How would you rate your new {b} gadget?',
    calc: {
      calcType: 'emi',
      promptText: 'Tap a cart value and a tenure — the EMI recalculates instantly, interest shown.',
      aLabel: 'Cart value', bLabel: 'Pay over',
      aOptions: [12999, 24999, 49999, 89999, 129999], bOptions: [1, 2, 3],
      ratePct: 15,
      resultLabel: 'Your monthly EMI',
      ctaLabel: 'Lock this EMI plan',
      doneLabel: 'Locked — approve in your bank app',
      dividerLabel: 'Living layer · composed at open',
      receiptTag: 'Untouched · your cart',
      receiptRows: [
        { k: 'Cart ref', v: 'CRT-9482017' },
        { k: 'In the cart', v: '4K Action Camera + 1TB SSD' },
        { k: 'Price lock', v: '48 hours' },
      ],
      footerText: 'EMI illustration only — your card issuer sets the final rate. Nothing is charged inside this email.',
    },
    report: {
      reportNoun: 'device report', itemNoun: 'checks',
      receiptTag: 'Untouched · your devices',
      metaRows: [
        { k: 'Report', v: 'DEV-2026-1142' },
        { k: 'Devices linked', v: '4 registered' },
      ],
      dividerLabel: 'Personalised for you · composed at open',
      statusLabels: { normal: 'All good', attention: 'Action soon' },
      rows: [
        { name: 'Noise-Cancelling Earbuds', sub: 'Firmware', value: 'v2.4 · latest', status: 'normal', detail: 'Updated over the air last week. Battery cycle count is healthy for 8 months of use.' },
        { name: 'Smartwatch Series X', sub: 'Battery health', value: '87%', status: 'normal', detail: 'Typical for 14 months of daily wear. Below 80% is when a service-centre battery swap starts making sense.' },
        { name: 'Extended warranty', sub: 'Smartwatch Series X', value: '12 days left', status: 'attention', detail: 'Cover ends on the 23rd. Renewing before expiry keeps the no-inspection rate; after expiry the device needs a check first.' },
        { name: 'Fast-Charge Power Bank', sub: 'Safety recall check', value: 'Not affected', status: 'normal', detail: 'Your serial falls outside the recalled batch range. Nothing to do.' },
        { name: 'Portable SSD 1TB', sub: 'Backup reminder', value: '34 days since backup', status: 'attention', detail: 'Your last synced backup is over a month old. A scheduled weekly backup takes one toggle in the app.' },
      ],
      verdictAction: 'a warranty and a backup are the two things worth doing this week.',
      verdictCta: 'See what it means',
      nextPrompt: 'Handle the warranty',
      slotLabels: ['Renew 1 year', 'Renew 2 years', 'Remind me later'],
      pickPrompt: 'Pick a renewal first',
      ctaLabel: 'Lock it',
      doneLabel: '✓ Locked — pay in the app to finish',
      footerText: 'Device data comes from your linked {b} account, read at open.',
    },
  },
  Travel: {
    items: [
      { name: 'Goa Beach Escape (3N)', price: 14999 },
      { name: 'Himalayan Trek Package', price: 21999 },
      { name: 'Bali Honeymoon (5N)', price: 48999 },
      { name: 'Weekend City Break', price: 8999 },
      { name: 'Airport Lounge Pass', price: 1299 },
      { name: 'Travel Insurance Plus', price: 799 },
    ],
    categories: ['Beach', 'Mountains', 'City'],
    catKeys: ['beach', 'mountains', 'city'],
    itemCats: ['beach', 'mountains', 'beach', 'city', 'city', 'city'],
    quiz: {
      q: 'Where is your next trip taking you?',
      options: [
        { label: 'Sun & sand', result: 'The {b} beach collection is ready toes in the sand, soon.' },
        { label: 'Peaks & trails', result: 'Lace up for the {b} mountain escapes fresh air awaits.' },
        { label: 'City lights', result: 'The {b} city breaks have your weekend planned go explore.' },
      ],
    },
    poll: { q: 'Dream {b} destination for 2026?', a: 'Japan', b: 'Iceland' },
    rate: 'How was your recent trip booked with {b}?',
    calc: {
      calcType: 'emi',
      promptText: 'Travel now, spread the cost — tap a trip budget and a tenure to see the monthly number.',
      aLabel: 'Trip budget', bLabel: 'Pay over',
      aOptions: [14999, 21999, 48999, 89999], bOptions: [1, 2, 3],
      ratePct: 13,
      resultLabel: 'Your monthly EMI',
      ctaLabel: 'Check my eligibility',
      doneLabel: 'Request sent — decision in the {b} app',
      dividerLabel: 'Living layer · composed at open',
      receiptTag: 'Untouched · your account',
      receiptRows: [
        { k: 'Traveller', v: 'Ananya S.' },
        { k: 'Watching', v: 'Bali · Dec 2026' },
        { k: 'Fare alerts', v: 'On · 3 this week' },
      ],
      footerText: 'EMI illustration only — the lender sets the final rate after eligibility. Nothing is charged inside this email.',
    },
    report: {
      reportNoun: 'trip readiness', itemNoun: 'checks',
      receiptTag: 'Untouched · your booking',
      metaRows: [
        { k: 'Trip', v: 'Goa · 14–17 Aug' },
        { k: 'Booking', v: 'TRP-48261193' },
        { k: 'Travellers', v: '2 adults' },
      ],
      attachmentName: 'Goa-Itinerary-TRP48261193.pdf',
      attachmentMeta: '3 pages · secure download',
      dividerLabel: 'Live status · composed at open',
      statusLabels: { normal: 'Sorted', attention: 'Needs you' },
      rows: [
        { name: 'Flights', sub: 'BLR → GOI · 6E-345', value: 'Confirmed', status: 'normal', detail: 'PNR X4B2QZ, both travellers ticketed. Web check-in opens 48 hours before departure.' },
        { name: 'Hotel', sub: 'Beachfront · 3 nights', value: 'Confirmed', status: 'normal', detail: 'Sea-view room held with early check-in requested. The property confirms early check-in on the day itself.' },
        { name: 'Web check-in', sub: 'Both travellers', value: 'Opens in 2 days', status: 'attention', detail: 'We can auto check-in the moment the window opens and send boarding passes to this thread.' },
        { name: 'Travel cover', sub: 'Monsoon week', value: 'Not added', status: 'attention', detail: 'August in Goa means delay risk. Flight-delay cover for both travellers costs less than one airport meal.' },
        { name: 'Airport transfer', sub: 'GOI → hotel', value: 'Not booked', status: 'normal', detail: 'Prepaid cabs at GOI are plentiful — booking ahead mainly buys a fixed price.' },
      ],
      verdictAction: 'check-in and monsoon cover are the two loose ends.',
      verdictCta: 'See what it means',
      nextPrompt: 'Tie up the loose ends',
      slotLabels: ['Auto check-in for me', 'Add delay cover', 'Book the transfer'],
      pickPrompt: 'Pick a task first',
      ctaLabel: 'Set it up',
      doneLabel: '✓ Done — confirmation on its way',
      footerText: 'Booking status is read live from your {b} trip at open.',
    },
  },
  Generic: {
    items: [
      { name: 'Starter Plan', price: 499 },
      { name: 'Pro Plan', price: 1499 },
      { name: 'Team Bundle', price: 3999 },
      { name: 'Annual Saver', price: 9999 },
      { name: 'Add-on Pack', price: 299 },
      { name: 'Premium Support', price: 1999 },
    ],
    categories: ['Plans', 'Add-ons', 'Support'],
    catKeys: ['plans', 'addons', 'support'],
    itemCats: ['plans', 'plans', 'plans', 'plans', 'addons', 'support'],
    quiz: {
      q: 'What brings you to {b} today?',
      options: [
        { label: 'Just exploring', result: 'Start with the {b} free tour no commitment, all the highlights.' },
        { label: 'Ready to commit', result: 'The {b} Pro plan unlocks everything you came for.' },
        { label: 'Scaling a team', result: 'The {b} team bundle grows with you seats, tools, support.' },
      ],
    },
    poll: { q: 'What should {b} build next?', a: 'Mobile app', b: 'Integrations' },
    rate: 'How likely are you to recommend {b}?',
    calc: {
      calcType: 'plan',
      promptText: 'Pay-as-you-go credits, or the flat Pro plan — tap your team size and usage to see which wins.',
      aLabel: 'Credits per seat / month', bLabel: 'Seats on the team',
      aOptions: [5, 10, 20, 40], bOptions: [1, 2, 5, 10],
      perUseFee: 99, planPrice: 1499,
      resultLabel: 'You would save every month',
      ctaLabel: 'Talk to us about Pro',
      doneLabel: 'Request sent — we will email a quote',
      dividerLabel: 'Living layer · composed at open',
      receiptTag: 'Untouched · your workspace',
      receiptRows: [
        { k: 'Workspace', v: 'acme-hq' },
        { k: 'Current plan', v: 'Starter · monthly' },
        { k: 'Last invoice', v: 'INV-2026-77120' },
      ],
      footerText: 'Estimates use last month’s metered usage. Nothing is ever charged inside this email.',
    },
    report: {
      reportNoun: 'account summary', itemNoun: 'checks',
      receiptTag: 'Untouched · your workspace',
      metaRows: [
        { k: 'Workspace', v: 'acme-hq' },
        { k: 'Billing period', v: '1–31 Jul' },
        { k: 'Summary', v: 'ACC-2026-0711' },
      ],
      dividerLabel: 'Personalised for you · composed at open',
      statusLabels: { normal: 'Healthy', attention: 'Needs a look' },
      rows: [
        { name: 'Seats in use', sub: 'Starter plan', value: '4 of 5', status: 'normal', detail: 'One seat free. Adding a sixth would tip you into the Team tier, which is cheaper per seat anyway.' },
        { name: 'Storage', sub: 'Files + exports', value: '82% full', status: 'attention', detail: 'At the current pace you hit the cap in about 3 weeks. Archiving stale exports usually claws back 20-30%.' },
        { name: 'API usage', sub: 'This period', value: 'Within plan', status: 'normal', detail: 'Peak day used 61% of your rate limit. No throttling events this month.' },
        { name: 'Renewal', sub: 'Card on file', value: 'In 9 days', status: 'attention', detail: 'The saved card expired last month — updating it now avoids a lapse and the re-onboarding dance.' },
        { name: 'Security posture', sub: 'Workspace-wide', value: '2FA on · 0 alerts', status: 'normal', detail: 'All members have two-factor enabled and there were no unusual sign-ins this period.' },
      ],
      verdictAction: 'billing and storage are the two things to touch before renewal day.',
      verdictCta: 'See what it means',
      nextPrompt: 'Sort it now',
      slotLabels: ['Update billing card', 'Add storage', 'Talk to support'],
      pickPrompt: 'Pick an action first',
      ctaLabel: 'Confirm',
      doneLabel: '✓ Requested — confirmation email coming',
      footerText: 'Workspace numbers are read at open. Informational, not a bill.',
    },
  },
};

function getContent(vertical) {
  return CONTENT[vertical] || CONTENT.Generic;
}

function applyBrand(str, brand) {
  return String(str).replace(/\{b\}/g, brand);
}

module.exports = { VERTICALS, TONES, CONTENT, getContent, applyBrand };
